open:
    app_token : 2l9Wyibysm
    app_secret: YsXg4n3PCX6beVapWI2XUrmE6c4fEx
    openurl: http://192.168.40.210:9182
oss:
    oss_url: http://43.159.49.39:9181
sign:
  sign_url: http://192.168.40.210:9180
cloud:
  cloud_url: https://crm.qiyuesuo.me/api
  X-Qys-Oss-Token: cb6335fe-007d-46f8-8f99-698a8b05ee79
auth:
  auth_url: https://person-auth.qiyuesuo.cn
