sign_token: 8b32b620-463e-4da3-a99d-9295d83136e3
empId: '3141663181004722972'
userId: '3141663180887282458'
auth_url: https://person-auth.qiyuesuo.me
user_authurl: https://person-auth.qiyuesuo.me?ticket=8KRcHanHDxxch4vYITcSWHeUYlweZs7ipFnNyPYFVzWpiDqu8z%2FvZbM2lR61Z%2B0B&channel=PRIVATE
