open:
    app_token : Kidx7OMpS3
    app_secret: VuxCTwaBccN37Mb4eMvgTHNcae8LaU
    openurl: http://192.168.40.210:9182
oss:
    oss_url: http://192.168.40.210:9181
cloud:
  cloud_url: https://crm.qiyuesuo.me/api
  X-Qys-Oss-Token: 65b97ee1-38d6-4b6c-b790-4f415c68dba7
  X-Auth-Qid: 65b97ee1-38d6-4b6c-b790-4f415c68dba7

