open:
    app_token : Kidx7OMpS3
    app_secret: VuxCTwaBccN37Mb4eMvgTHNcae8LaU
    openurl: http://192.168.40.210:9182
oss:
    oss_url: http://192.168.40.210:9181
cloud:
  cloud_url: https://crm.qiyuesuo.me/api
  X-Qys-Oss-Token: 5d53c73d-fb1d-4735-81c7-118a8c36b963
  X-Auth-Qid: 5d53c73d-fb1d-4735-81c7-118a8c36b963

