open:
    app_token : Kidx7OMpS3
    app_secret: VuxCTwaBccN37Mb4eMvgTHNcae8LaU
    openurl: http://192.168.40.210:9182
cloud:
  cloud_url: https://crm.qiyuesuo.me/api
  X-Qys-Oss-Token: 51dd317f-eb57-44e4-93b0-1e54d2e9ae98
  X-Auth-Qid: 51dd317f-eb57-44e4-93b0-1e54d2e9ae98

