open:
    app_token : Kidx7OMpS3
    app_secret: VuxCTwaBccN37Mb4eMvgTHNcae8LaU
    openurl: http://192.168.40.210:9182
cloud:
  cloud_url: https://crm.qiyuesuo.me/api
  X-Qys-Oss-Token: faa24c24-6e1c-4546-b8c7-0c25ec7b09b7
  X-Auth-Qid: faa24c24-6e1c-4546-b8c7-0c25ec7b09b7

