open:
    app_token : 2l9Wyibysm
    app_secret: YsXg4n3PCX6beVapWI2XUrmE6c4fEx
    openurl: http://192.168.40.210:9182
oss:
    oss_url: http://oss84.qiyuesuo.net
sign:
  app_url: http://app84.qiyuesuo.net
cloud:
  cloud_url: https://crm.qiyuesuo.me/api
  X-Qys-Oss-Token: 573fc2fe-3a5f-4723-9891-26a24db8a895
